### ISSUE TITLE
Add Enterprise Deployment clarity to README.md

### ISSUE THREAD

**Issue by jamasten** [JCoreMS/AVDAlerts#20]
The global admin assigning owner to the root scope to a principal cannot be the same user as the principal.

**Comment by JCoreMS** [comment]
This is the document that is needed but based on this solution I will clarify the exact pre-reqs in the document soon. 
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant?tabs=azure-cli

**Comment by JCoreMS** [comment]
Updated documentation and even added the needed command in the Deployment PS1 for tenant wide deployment.
