### ISSUE TITLE
Bug: Automation Account can't read Storage Account with custom endpoints (Temp removed from solution)

### ISSUE THREAD

**Issue by jamasten** [JCoreMS/AVDAlerts#21]
The Automation Account throws a 403 error with the storage runbook when service or private endpoints are enabled on the storage account.

**Comment by jamasten** [comment]
We should look into deploying a hybrid worker on the automation account that's on a supported subnet to talk to the storage account when service or privates are enabled

**Comment by jamasten** [comment]
This might also be resolved by putting a private endpoint for the automation account on the same subnet that has the private or service endpoint for the storage account.

**Comment by jamasten** [comment]
@JCoreMS, how did you resolve this?

**Comment by JCoreMS** [comment]
Re-added with updates noted in readme.md.  This was an issue with permissions on the Automation Account and resolved.
