### ISSUE TITLE
Bug: Storage-Over 200ms Latency alerts with no usage

### ISSUE THREAD

**Issue by jamasten** [JCoreMS/AVDAlerts#22]
This alert seems to be creating a bunch of noise in my environment and I'm not even using the storage account.

**Comment by jamasten** [comment]
I had a customer that stated 50ms was the desired threshold.  Need to validate the number.

**Comment by brmcmill** [comment]
We can't validate this until we get the Storage Alerting to work with Service Endpoints (and Private for that matter).  Can provide more feedback once that fix is in place/ready to go.

**Comment by brmcmill** [comment]
Is there anything internal that states a desired threshold?  Definitely 10-20 ms is too low from my experience.  50 seems reasonable, 200 seemed high.

**Comment by JCoreMS** [comment]
I'm not actually seeing this triggered in my environment.  I will certainly look into the criteria and what is recommended.

**Comment by JCoreMS** [comment]
I believe this was derived from this article which is for Standard Storage Blob accounts so will determine appropriate metric and adjust.
https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account?source=recommendations

**Comment by JCoreMS** [comment]
Will adjust to the following:
2 Alerts for Storage Latency 50ms / 100 ms
2 Alerts for End 2 End Latency 50ms / 100 ms
https://learn.microsoft.com/en-us/azure/storage/files/storage-files-monitoring-reference#transaction-metrics
And adding how to review in description based on:
https://learn.microsoft.com/en-us/azure/storage/files/storage-troubleshooting-files-performance#very-high-latency-for-requests
