### ISSUE TITLE
AVD-VM-FSLogix Profile Failed - More Streamlined Log Query

### ISSUE THREAD

**Issue by brmcmill** [JCoreMS/AVDAlerts#24]
While this alert is very helpful, I believe the log query can focus more specifics on FSLogix Profile Failure issues.  I'm concerned if say there is a massive storage issue, this alert will provide a storm of messages unnecessary for the customer.  Here's some EventIds that may be helpful along with some descriptions to consider.  Happy to test:

**EventID**: 33
**RenderedDescription**: The user vhd(x) (VHDPath ... has less than 200 MB free space left and must be expanded...
**ParamterXML Example**: ...ErrorCode: 112.  ErrorMessage: There is not enough space on the disk...

**EventID**: 56
**RenderedDescription**: Failed to reattach VHD for user <no data>
**ParamterXML Example**: ...ErrorCode: 5.  ErrorMessage: Access is denied...

**Comment by JCoreMS** [comment]
@brmcmill are the noted events in the Admin or Operations logs for FSLogix?

**Comment by brmcmill** [comment]
@JCoreMS  -- I know you closed this, was curious what you ended up deciding to do.  I'm going to do analysis real quick on your ask and post it here anyway just for record.

**Comment by brmcmill** [comment]
@JCoreMS  -- Microsoft-FSLogix-Apps/Admin
