### ISSUE TITLE
Feature Request: Provided RBAC model to Deploy Enterprise Solution without Need for Tenant Owner

### ISSUE THREAD

**Issue by brmcmill** [JCoreMS/AVDAlerts#28]
Having flexibility for admins that may not have Global Administrator or Tenant Ownership will provide more flexibility leveraging a secure RBAC model to deploy the Enterprise Solution.  Either way that makes this more flexible the better.  Hope this helps!

**Comment by JCoreMS** [comment]
Updated DeployToTenant.ps1 to have error handling but in the case of deploying to a Tenant the user must have owner at that level. Previously the script only checked to see if the root '/' was empty and if so would try to assign the current user. This also did not factor in or check group memberships.

Added a function for adding user to Tenant level as owner with error handling and output that references the noted article.
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant?tabs=azure-cli#required-access

Logic is as follows:
- get owners at Tenant level
- if none, function to add current user
- if users or groups, checks for current user and if not found will list groups and ask if member of any listed groups with owner
- if no, then will execute function to add current user
- any selections to not add the user or acknowledge they are not an existing group member will exit with information
